# Generated by Django 3.1.6 on 2021-02-05 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcdashadmin', '0002_auto_20210204_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='store',
        ),
    ]
