# Generated by Django 3.1.6 on 2021-02-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcdashadmin', '0004_staff_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
